name: Token after merge
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update the package
        run: |
          swift package update
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
            token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            repository: Aishwaryalaxmi/Repo2
            event-type: sample_push
